default:
    study_name: "C. elegans L2 Data"
    study_description: "Data from Cao, Junyue, et al. Comprehensive single-cell transcriptional profiling of a multicellular organism. Science 357.6352 (2017): 661-667."
    organism: "cel" # choose from mmu (mouse), hsa (human) and cel (C.elegans)
    feature_name_column: "symbol"
    feature_id_column: "id" # Set this to be same as name col if feature id column not available
